# Generated by Django 3.1.6 on 2021-02-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Links',
        ),
    ]
