# Generated by Django 3.1.6 on 2021-02-13 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shorter_app', '0002_auto_20210213_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='links',
            old_name='user_token',
            new_name='user_id',
        ),
    ]
