# Generated by Django 3.1.6 on 2021-02-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorter_app', '0003_auto_20210213_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorter_app.users'),
        ),
    ]
